name: Build Docs
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  nim-version: 'stable'
  nim-src: src/${{ github.event.repository.name }}.nim
  deploy-dir: .gh-pages
  package-name: modernnet

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ env.nim-version }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - run: nimble install -Y

      - run: nimble doc --index:on --project --git.url:https://github.com/${{ github.repository }} --git.commit:${{ github.ref_name }} --out:${{ env.deploy-dir }} ${{ env.nim-src }}

      - name: "Copy to index.html"
        run: cp ${{ env.deploy-dir }}/${{ env.package-name }}.html ${{ env.deploy-dir }}/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{ env.deploy-dir }}

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1